Redo waiting for pod

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -109,7 +109,22 @@ jobs:
           EOF
 
           # Wait until the catalog source of our operator is up and running
-          # kubectl wait --for=condition=ready pod -n $K8S_NAMESPACE --selector=olm.catalogSource=joke-operator --timeout=120s
+          retries=30
+          until [[ $retries == 0 ]]; do
+            new_phase=$(kubectl get pods -n $K8S_NAMESPACE --selector=olm.catalogSource=joke-operator -o jsonpath='{..status.phase}' 2>/dev/null || echo "Waiting for pod to appear")
+            if [[ "$new_phase" == "Running" ]]; then
+              break
+            elif [[ $retries == 1 ]]; then
+              echo "Pod failed to reach phase Running"
+              exit 1
+            else
+              kubectl get events -n $K8S_NAMESPACE
+              kubectl logs -n $K8S_NAMESPACE --selector=olm.catalogSource=joke-operator
+              echo "Pod phase: $new_phase"
+            fi
+            sleep 10s
+            retries=$((retries - 1))
+          done
 
           # Create a Subscription which triggers the deployment of joke operator
           cat <<EOF | kubectl create -f -
@@ -135,10 +150,6 @@ jobs:
               echo "CSV \"jokerequestreconciler\" failed to reach phase succeeded"
               exit 1
             else
-              kubectl get events -n $K8S_NAMESPACE
-              kubectl get pod -n $K8S_NAMESPACE --selector=olm.catalogSource=joke-operator
-              kubectl logs -n $K8S_NAMESPACE --selector=olm.catalogSource=joke-operator
-              kubectl get events -n $K8S_NAMESPACE
               echo "CSV \"jokerequestreconciler\" phase: $new_csv_phase"
             fi
             sleep 10s
